### ISSUE TITLE
Make Sulakore trimmable

### ISSUE THREAD

**Issue by PaulusParssinen** [ArachisH/Sulakore#38]
Basically follow this guide from Microsoft: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming.

Currently I can think of some string -> Enum parsing logic in `Sulakore.Habbo.HExtensions` being a problem. `System.Text.Json` probably also needs some extra care.

### TODO
  - [x] `Sulakore.Habbo.Web` JSON deserialization to use source generators
  - [x] `Sulakore.Habbo.Camera` JSON (de)serialization to use source generators
  - [x] Enums. Solution: We need to parse enums only in one place for now. Made internal reflection-free parser to handle this. We can consider either to consume enum source generator or make our own if this becomes more common in the SDK or if its consumers want it.
